/*
 * Generated by MTK SP Drv_CodeGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Dec 25 18:48:56 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


